### ISSUE TITLE
linux下编译和运行不了。

### ISSUE THREAD

**Issue by lantianning** [azraelrabbit/chromiumfx-git#1]
大神，请教一下。这个项目能在linux下编译和运行吗？windows的我已经测试成功了。我从bitbucket.org追过来请教你了。我用的ide是Monodevelop 5.10。

**Comment by azraelrabbit** [comment]
不好意思.实在用不惯bitbucket 和 hg.
在linux下能编译成功的.
只能用monodevelop 5.10 编译.
你确认打开的是 ChromiumFX-Mono.sln 这个解决方案么?
windows下 用 ChromiumFX.sln , linux 下用 ChromiumFX-Mono.sln

**Comment by lantianning** [comment]
听到你说能编译，我的心就总算安定了。我再确认一下。

**Comment by lantianning** [comment]
我下载的版本没有ChromiumFX-Mono.sln，我再试试确认一下。

**Comment by lantianning** [comment]
i dont know what s worry?
--------------------------------------
mono CfxTestBrowser.exe
init args:
lang-list
ua
[1024/234158.116873:ERROR:context.cc(344)] Not implemented reached in bool CefContext::Initialize(const CefMainArgs &, const CefSettings &, CefRefPtr<CefApp>, void *)multi_threaded_message_loop is not supported.

Unhandled Exception:
Chromium.WebBrowser.ChromiumWebBrowserException: Failed to initialize CEF library.
  at Chromium.WebBrowser.BrowserProcess.Initialize () [0x0010b] in <74e5834b17b94aa0bd26ba4b8f99c2e4>:0 
  at Chromium.WebBrowser.ChromiumWebBrowser.Initialize () [0x00001] in <74e5834b17b94aa0bd26ba4b8f99c2e4>:0 
  at ceftest.Program.Main (System.String[] args) [0x0005f] in <97caa246387345a3b11a865fc0340d6a>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: Chromium.WebBrowser.ChromiumWebBrowserException: Failed to initialize CEF library.
  at Chromium.WebBrowser.BrowserProcess.Initialize () [0x0010b] in <74e5834b17b94aa0bd26ba4b8f99c2e4>:0 
  at Chromium.WebBrowser.ChromiumWebBrowser.Initialize () [0x00001] in <74e5834b17b94aa0bd26ba4b8f99c2e4>:0 
  at ceftest.Program.Main (System.String[] args) [0x0005f] in <97caa246387345a3b11a865fc0340d6a>:0

**Comment by lantianning** [comment]
另外，我的linux开发机的配置比较低，是32位ATOM的CPU，操作系统是ubuntu mate 15。这些有没有什么限制？我的MonoDevelper 5.10稳定性好差，经常会闪退。

**Comment by lantianning** [comment]
mono WindowsFormsApplication.exe 

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000020

**Comment by lantianning** [comment]
在linux下 MonoDevelop能编译libcefx这个项目，但是其他项目都不能编译。

**Comment by lantianning** [comment]
Building: ChromiumFX (Debug)

Build started 10/25/2017 1:09:22 AM.
__________________________________________________
Project "/home/lan/Downloads/chromiumfx-git-master/ChromiumFX/ChromiumFX.csproj" (Build target(s)):
	
	Target PrepareForBuild:
		Configuration: Debug Platform: AnyCPU
	
	Target GenerateSatelliteAssemblies:
	No input files were specified for target GenerateSatelliteAssemblies, skipping.
	
	Target _GenerateTargetFrameworkMonikerAttribute:
	Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
	
	Target CoreCompile:
		Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/ChromiumFX.dll Properties/AssemblyInfo.cs Generated/CfxAccessibilityHandler.cs Generated/CfxApi.cs Generated/CfxApiLoader.cs Generated/CfxApp.cs Generated/CfxAuthCallback.cs Generated/CfxBeforeDownloadCallback.cs Generated/CfxBinaryValue.cs Generated/CfxBoxLayoutSettings.cs Generated/CfxBrowser.cs Generated/CfxBrowserHost.cs Generated/CfxBrowserProcessHandler.cs Generated/CfxBrowserSettings.cs Generated/CfxCallback.cs Generated/CfxClient.cs Generated/CfxCommandLine.cs Generated/CfxCompletionCallback.cs Generated/CfxCompositionUnderline.cs Generated/CfxContextMenuHandler.cs Generated/CfxContextMenuParams.cs Generated/CfxCookie.cs Generated/CfxCookieManager.cs Generated/CfxCookieVisitor.cs Generated/CfxCursorInfo.cs Generated/CfxDeleteCookiesCallback.cs Generated/CfxDialogHandler.cs Generated/CfxDictionaryValue.cs Generated/CfxDisplayHandler.cs Generated/CfxDomDocument.cs Generated/CfxDomNode.cs Generated/CfxDomVisitor.cs Generated/CfxDownloadHandler.cs Generated/CfxDownloadImageCallback.cs Generated/CfxDownloadItem.cs Generated/CfxDownloadItemCallback.cs Generated/CfxDragData.cs Generated/CfxDraggableRegion.cs Generated/CfxDragHandler.cs Generated/CfxEndTracingCallback.cs Generated/CfxEnums.cs Generated/CfxFileDialogCallback.cs Generated/CfxFindHandler.cs Generated/CfxFocusHandler.cs Generated/CfxFrame.cs Generated/CfxGeolocationCallback.cs Generated/CfxGeolocationHandler.cs Generated/CfxGeoposition.cs Generated/CfxGetGeolocationCallback.cs Generated/CfxImage.cs Generated/CfxInsets.cs Generated/CfxJsDialogCallback.cs Generated/CfxJsDialogHandler.cs Generated/CfxKeyboardHandler.cs Generated/CfxKeyEvent.cs Generated/CfxLifeSpanHandler.cs Generated/CfxListValue.cs Generated/CfxLoadHandler.cs Generated/CfxMainArgsLinux.cs Generated/CfxMainArgsWindows.cs Generated/CfxMenuModel.cs Generated/CfxMenuModelDelegate.cs Generated/CfxMouseEvent.cs Generated/CfxNavigationEntry.cs Generated/CfxNavigationEntryVisitor.cs Generated/CfxPdfPrintCallback.cs Generated/CfxPdfPrintSettings.cs Generated/CfxPoint.cs Generated/CfxPopupFeatures.cs Generated/CfxPostData.cs Generated/CfxPostDataElement.cs Generated/CfxPrintDialogCallback.cs Generated/CfxPrintHandler.cs Generated/CfxPrintJobCallback.cs Generated/CfxPrintSettings.cs Generated/CfxProcessMessage.cs Generated/CfxRange.cs Generated/CfxReadHandler.cs Generated/CfxRect.cs Generated/CfxRegisterCdmCallback.cs Generated/CfxRenderHandler.cs Generated/CfxRenderProcessHandler.cs Generated/CfxRequest.cs Generated/CfxRequestCallback.cs Generated/CfxRequestContext.cs Generated/CfxRequestContextHandler.cs Generated/CfxRequestContextSettings.cs Generated/CfxRequestHandler.cs Generated/CfxResolveCallback.cs Generated/CfxResourceBundle.cs Generated/CfxResourceBundleHandler.cs Generated/CfxResourceHandler.cs Generated/CfxResponse.cs Generated/CfxResponseFilter.cs Generated/CfxRunContextMenuCallback.cs Generated/CfxRunFileDialogCallback.cs Generated/CfxRuntime.cs Generated/CfxSchemeHandlerFactory.cs Generated/CfxSchemeRegistrar.cs Generated/CfxScreenInfo.cs Generated/CfxSelectClientCertificateCallback.cs Generated/CfxSetCookieCallback.cs Generated/CfxSettings.cs Generated/CfxSize.cs Generated/CfxSslInfo.cs Generated/CfxSslStatus.cs Generated/CfxStreamReader.cs Generated/CfxStreamWriter.cs Generated/CfxStringVisitor.cs Generated/CfxTask.cs Generated/CfxTaskRunner.cs Generated/CfxThread.cs Generated/CfxTime.cs Generated/CfxUrlParts.cs Generated/CfxUrlRequest.cs Generated/CfxUrlRequestClient.cs Generated/CfxV8Accessor.cs Generated/CfxV8Context.cs Generated/CfxV8Exception.cs Generated/CfxV8Handler.cs Generated/CfxV8Interceptor.cs Generated/CfxV8StackFrame.cs Generated/CfxV8StackTrace.cs Generated/CfxV8Value.cs Generated/CfxValue.cs Generated/CfxWaitableEvent.cs Generated/CfxWebPluginInfo.cs Generated/CfxWebPluginInfoVisitor.cs Generated/CfxWebPluginUnstableCallback.cs Generated/CfxWindowInfoLinux.cs Generated/CfxWindowInfoWindows.cs Generated/CfxWriteHandler.cs Generated/CfxX509Certificate.cs Generated/CfxX509CertPrincipal.cs Generated/CfxXmlReader.cs Generated/CfxZipReader.cs Generated/Remote/CfrApp.cs Generated/Remote/CfrBinaryValue.cs Generated/Remote/CfrBrowser.cs Generated/Remote/CfrCommandLine.cs Generated/Remote/CfrDictionaryValue.cs Generated/Remote/CfrDomDocument.cs Generated/Remote/CfrDomNode.cs Generated/Remote/CfrDomVisitor.cs Generated/Remote/CfrFrame.cs Generated/Remote/CfrListValue.cs Generated/Remote/CfrLoadHandler.cs Generated/Remote/CfrPostData.cs Generated/Remote/CfrPostDataElement.cs Generated/Remote/CfrProcessMessage.cs Generated/Remote/CfrReadHandler.cs Generated/Remote/CfrRect.cs Generated/Remote/CfrRenderProcessHandler.cs Generated/Remote/CfrRequest.cs Generated/Remote/CfrResourceBundle.cs Generated/Remote/CfrResourceBundleHandler.cs Generated/Remote/CfrResponse.cs Generated/Remote/CfrRuntime.cs Generated/Remote/CfrSchemeRegistrar.cs Generated/Remote/CfrStreamReader.cs Generated/Remote/CfrStreamWriter.cs Generated/Remote/CfrStringVisitor.cs Generated/Remote/CfrTask.cs Generated/Remote/CfrTaskRunner.cs Generated/Remote/CfrThread.cs Generated/Remote/CfrTime.cs Generated/Remote/CfrV8Accessor.cs Generated/Remote/CfrV8Context.cs Generated/Remote/CfrV8Exception.cs Generated/Remote/CfrV8Handler.cs Generated/Remote/CfrV8Interceptor.cs Generated/Remote/CfrV8StackFrame.cs Generated/Remote/CfrV8StackTrace.cs Generated/Remote/CfrV8Value.cs Generated/Remote/CfrValue.cs Generated/Remote/CfrWaitableEvent.cs Generated/Remote/CfrWriteHandler.cs Generated/Remote/CfrXmlReader.cs Generated/Remote/CfrZipReader.cs Generated/Remote/CfxAppRemoteCalls.cs Generated/Remote/CfxAppRemoteClient.cs Generated/Remote/CfxBinaryValueRemoteCalls.cs Generated/Remote/CfxBrowserRemoteCalls.cs Generated/Remote/CfxCommandLineRemoteCalls.cs Generated/Remote/CfxDictionaryValueRemoteCalls.cs Generated/Remote/CfxDomDocumentRemoteCalls.cs Generated/Remote/CfxDomNodeRemoteCalls.cs Generated/Remote/CfxDomVisitorRemoteCalls.cs Generated/Remote/CfxDomVisitorRemoteClient.cs Generated/Remote/CfxFrameRemoteCalls.cs Generated/Remote/CfxListValueRemoteCalls.cs Generated/Remote/CfxLoadHandlerRemoteCalls.cs Generated/Remote/CfxLoadHandlerRemoteClient.cs Generated/Remote/CfxPostDataElementRemoteCalls.cs Generated/Remote/CfxPostDataRemoteCalls.cs Generated/Remote/CfxProcessMessageRemoteCalls.cs Generated/Remote/CfxReadHandlerRemoteCalls.cs Generated/Remote/CfxReadHandlerRemoteClient.cs Generated/Remote/CfxRectRemoteCalls.cs Generated/Remote/CfxRenderProcessHandlerRemoteCalls.cs Generated/Remote/CfxRenderProcessHandlerRemoteClient.cs Generated/Remote/CfxRequestRemoteCalls.cs Generated/Remote/CfxResourceBundleHandlerRemoteCalls.cs Generated/Remote/CfxResourceBundleHandlerRemoteClient.cs Generated/Remote/CfxResourceBundleRemoteCalls.cs Generated/Remote/CfxResponseRemoteCalls.cs Generated/Remote/CfxRuntimeRemoteCalls.cs Generated/Remote/CfxSchemeRegistrarRemoteCalls.cs Generated/Remote/CfxStreamReaderRemoteCalls.cs Generated/Remote/CfxStreamWriterRemoteCalls.cs Generated/Remote/CfxStringVisitorRemoteCalls.cs Generated/Remote/CfxStringVisitorRemoteClient.cs Generated/Remote/CfxTaskRemoteCalls.cs Generated/Remote/CfxTaskRemoteClient.cs Generated/Remote/CfxTaskRunnerRemoteCalls.cs Generated/Remote/CfxThreadRemoteCalls.cs Generated/Remote/CfxTimeRemoteCalls.cs Generated/Remote/CfxV8AccessorRemoteCalls.cs Generated/Remote/CfxV8AccessorRemoteClient.cs Generated/Remote/CfxV8ContextRemoteCalls.cs Generated/Remote/CfxV8ExceptionRemoteCalls.cs Generated/Remote/CfxV8HandlerRemoteCalls.cs Generated/Remote/CfxV8HandlerRemoteClient.cs Generated/Remote/CfxV8InterceptorRemoteCalls.cs Generated/Remote/CfxV8InterceptorRemoteClient.cs Generated/Remote/CfxV8StackFrameRemoteCalls.cs Generated/Remote/CfxV8StackTraceRemoteCalls.cs Generated/Remote/CfxV8ValueRemoteCalls.cs Generated/Remote/CfxValueRemoteCalls.cs Generated/Remote/CfxWaitableEventRemoteCalls.cs Generated/Remote/CfxWriteHandlerRemoteCalls.cs Generated/Remote/CfxWriteHandlerRemoteClient.cs Generated/Remote/CfxXmlReaderRemoteCalls.cs Generated/Remote/CfxZipReaderRemoteCalls.cs Generated/Remote/RemoteCallFactory.cs Generated/Remote/RemoteCallId.cs Source/CfxApi.cs Source/CfxArray.cs Source/CfxBaseRefCounted.cs Source/CfxBaseScoped.cs Source/CfxBinaryValue.cs Source/CfxBaseClient.cs Source/CfxColor.cs Source/CfxDebug.cs Source/CfxBaseLibrary.cs Source/CfxMainArgsLinux.cs Source/CfxPlatform.cs Source/CfxRemoteCallbackManager.cs Source/CfxRemoteCallContext.cs Source/CfxTime.cs Source/CfxV8Value.cs Source/CfxWindowInfo.cs Source/NativeFunctionLoader.cs Source/CfxMainArgs.cs Source/Remote/CfrBaseLibrary.cs Source/Remote/CfrBaseClient.cs Source/Remote/CfrMayBlockEventArgs.cs Source/Remote/CfrTellEventArgs.cs Source/Remote/CfrSeekEventArgs.cs Source/Remote/CfrBaseScoped.cs Source/Remote/WorkerPool.cs Source/StringFunctions.cs Source/CfxZipReader.cs Source/Remote/CfrTime.cs Source/Remote/CfrBinaryValue.cs Source/Remote/CfrEventArgs.cs Source/CfxException.cs Source/CfxObject.cs Source/PinnedObject.cs Source/PinnedString.cs Source/Remote/CfrBaseRefCounted.cs Source/CfxEventArgs.cs Source/Remote/CfrObject.cs Source/Remote/CfrRuntime.cs Source/Remote/CfrV8Value.cs Source/Remote/CfrStructure.cs Source/Remote/CfrMarshal.cs Source/Remote/RemoteCall.cs Source/Remote/RemoteConnection.cs Source/Remote/RemoteCallBases.cs Source/Remote/RemotePtr.cs Source/Remote/StreamHandler.cs Source/Remote/RemoteClient.cs Source/Remote/RemoteService.cs Source/CfxRuntime.cs Source/CfxStructure.cs Source/TimeFunctions.cs Source/WeakCache.cs Source/WindowStyle.cs Source/Remote/DefaultPipeFactory.cs Source/Remote/PipeFactory.cs Source/Remote/PipBufferStream.cs obj/Debug/.NETFramework,Version=v4.0,Profile=Client.AssemblyAttribute.cs /target:library /unsafe+ /define:"TRACE;DEBUG" /nowarn:1591 /doc:../Build/Debug/ChromiumFX.xml /nostdlib /platform:AnyCPU /reference:/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll /reference:/usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll /warn:4
CSC: error CS0518: The predefined type `System.Object' is not defined or imported
CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
CSC: error CS0518: The predefined type `System.Single' is not defined or imported
CSC: error CS0518: The predefined type `System.Double' is not defined or imported
CSC: error CS0518: The predefined type `System.Char' is not defined or imported
CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
CSC: error CS0518: The predefined type `System.String' is not defined or imported
CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
CSC: error CS0518: The predefined type `System.Void' is not defined or imported
CSC: error CS0518: The predefined type `System.Array' is not defined or imported
CSC: error CS0518: The predefined type `System.Type' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.Exception' is not defined or imported
	Task "Csc" execution -- FAILED
	Done building target "CoreCompile" in project "/home/lantn/Downloads/chromiumfx-git-master/ChromiumFX/ChromiumFX.csproj".-- FAILED
	
Done building project "/home/lan/Downloads/chromiumfx-git-master/ChromiumFX/ChromiumFX.csproj".-- FAILED

Build FAILED.
Errors:

/home/lan/Downloads/chromiumfx-git-master/ChromiumFX/ChromiumFX.csproj (Build) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	CSC: error CS0518: The predefined type `System.Object' is not defined or imported
	CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
	CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
	CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
	CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
	CSC: error CS0518: The predefined type `System.Single' is not defined or imported
	CSC: error CS0518: The predefined type `System.Double' is not defined or imported
	CSC: error CS0518: The predefined type `System.Char' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
	CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
	CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
	CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
	CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
	CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
	CSC: error CS0518: The predefined type `System.String' is not defined or imported
	CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
	CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
	CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
	CSC: error CS0518: The predefined type `System.Void' is not defined or imported
	CSC: error CS0518: The predefined type `System.Array' is not defined or imported
	CSC: error CS0518: The predefined type `System.Type' is not defined or imported
	CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
	CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
	CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported

---------------------- Done ----------------------

Build: 31 errors, 0 warnings

**Comment by azraelrabbit** [comment]
昨天出差了, 晚上刚回. 明天找时间我再调试一下..
另外 我用的是 ubuntu 16.04.3  x64 mono 5.2 .. 你mono的版本是多少?

**Comment by lantianning** [comment]
我的是ubuntu mate 17.04 x32 mono4.6.2

**Comment by lantianning** [comment]
我的是ubuntu mate 17.04 x86 mono4.6.2

**Comment by azraelrabbit** [comment]
@lantianning  目前的开发分支在linux下确实存在问题,但是能够编译通过. 运行时会报错.
建议你先使用 https://github.com/azraelrabbit/chromiumfx-git/releases/tag/3.3071.1644.last.20170928
这个 release . 对应的 cef 版本是 3.3071.1644

**Comment by lantianning** [comment]
收到，晚点试一下。谢谢您了。

**Comment by azraelrabbit** [comment]
另外 注意一下 cef库 的路径位置,

**Comment by azraelrabbit** [comment]
刚刚调试了一下,目前开发分支下的代码在linux下可以正常运行,要注意的就是cef库的路径,
还有建议将mono升级到5.0以上的版本, 
5.0以下的版本未测试过,不保证能正常运行.

PS: 最近比较忙, 我会抽时间完善一下windowless模式组件的功能,
然后会放出完整的nuget包.
届时引用使用上会更方便.

**Comment by lantianning** [comment]
我重新测试过一下。因为CfxTestApplication项目对目录摆放有要求，我就自建了一个项目WindowsFormsApplication1。关键代码我在下一个回复上贴上。下面就报一下故障提示，看看大神有没有建议？
/cef_binary_3.3071.1644.g408afd1_linux32_client/Release$ mono WindowsFormsApplication1.exe
 ****************** window Less False
()()*()*(**()*)(*()*))
 --no-sandbox --lang=en-US --log-file=/usr/bin/debug.log --renderer-cmd-prefix --gpu-launcher=mono --utility-cmd-prefix=mono
[1029/232802.646380:ERROR:icu_util.cc(173)] Invalid file descriptor to ICU data received.
Trace/breakpoint trap (core dumped)

**Comment by lantianning** [comment]
Form1.cs
----------
using Chromium.WebBrowser;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace WindowsFormsApplication1
{
    
    public partial class Form1 : Form
    {
        private Chromium.WebBrowser.ChromiumWebBrowserBase webBrowser;
        public Form1()
        {
            InitializeComponent();
            ChromiumWebBrowser wb = new ChromiumWebBrowser(this);
            wb.Dock = DockStyle.Fill;
            this.Controls.Add(wb);
            wb.LoadUrl("http://www.baidu.com");
        }

        private void Form1_Load(object sender, EventArgs e)
        { }
            
    }
}
=================================================
Program.cs
------------------------------------------------------------------------------------
using Chromium;
using Chromium.WebBrowser;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Forms;

namespace WindowsFormsApplication1
{
    static class Program
    {
        /// <summary>
        /// 应用程序的主入口点。
        /// </summary>
        [STAThread]
        static void Main()
        {
            ChromiumWebBrowser.Initialize();
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
            CfxRuntime.Shutdown();
        }
    }
}

**Comment by azraelrabbit** [comment]
根据你的报错信息来看,你需要将icudtl.dat 复制到 你自建的.exe同目录下..
这个好像是 cef的一个坑.

**Comment by lantianning** [comment]
我看了，icudtl.dat文件是在同一个目录里的。

**Comment by azraelrabbit** [comment]
嗯. 开发分支目前可以用了. 打包发布到nuget上了.
https://www.nuget.org/packages/AZ.ChromiumFX/

对应的 cef package:
x64: for windows:
https://www.nuget.org/packages/AZ.ChromiumFX.Cef.win-x64/

x64 for linux:
https://www.nuget.org/packages/AZ.ChromiumFX.Cef.linux-x64/

x86 for windows:
https://www.nuget.org/packages/AZ.ChromiumFX.Cef.win-x86/

x86 for linux: 
https://www.nuget.org/packages/AZ.ChromiumFX.Cef.linux-x86/

**Comment by azraelrabbit** [comment]
用法简单: 
直接使用扩展库里封装的静态类:

	static class Program
    {
 

        /// <summary>
        /// 应用程序的主入口点。
        /// </summary>
        [STAThread]
        static void Main(string[] args)
        {
 
            //on windows use ChromiumfxWebBrowser set to false
            ChromiumStartup.RequireWindowLess = false;

            //on linux use chromiumfxWebBrowserWindowless set to true
            //ChromiumStartup.RequireWindowLess = true;

            // you can use your custome cef lib path 
            //var basePath = System.IO.Path.GetDirectoryName(new System.Uri(System.Reflection.Assembly.GetExecutingAssembly().CodeBase).LocalPath);
            //ChromiumStartup.LibCefPath = Path.Combine(basePath, "cef");
            //ChromiumStartup.LibCfxPath = Path.Combine(basePath, "cef");
            //ChromiumStartup.CefResourcePath = Path.Combine(basePath, "cef");// or Path.Combine(basePath, "cef","Resource");
 

            ChromiumStartup.Initialize();


            ChromiumStartup.RegisterLocalScheme();
 
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
 

        }

    }





	public partial class Form1 : Form
    {
		private Chromium.WebBrowser.ChromiumWebBrowser webBrowser;
 
        public Form1()
        {
           
        }

        private void Form1_Load(object sender, EventArgs e)
        {
              webBrowser=new ChromiumWebBrowser(this);
 
            webBrowser.Dock=DockStyle.Fill;
 
            webBrowser.LoadUrl("http://www.baidu.com");
 
        }

	}

**Comment by azraelrabbit** [comment]
建议你直接只用nuget包...使用相对比较简单

**Comment by lantianning** [comment]
好的，我回去试一下。

**Comment by lantianning** [comment]
我最终的想法是想在arm上使用。我另外还会编译一下arm版的cef bin。

**Comment by azraelrabbit** [comment]
哦.那就只需要 https://www.nuget.org/packages/AZ.ChromiumFX/

**Comment by lantianning** [comment]
/testcef/testcef/testcef/bin/Debug$ mono testcef.exe
Could not set X locale modifiers
 ****************** window Less False
()()*()*(**()*)(*()*))
/home/lantn/testcef/testcef/testcef/bin/Debug/testcef.exe --no-sandbox --lang=en-US --log-file=/usr/bin/debug.log --renderer-cmd-prefix --gpu-launcher=mono --utility-cmd-prefix=mono
[1103/220214.864672:WARNING:resource_bundle.cc(366)] locale_file_path.empty() for locale 
[1103/220214.864920:ERROR:main_delegate.cc(671)] Could not load locale pak for en-US
[1103/220214.865027:ERROR:main_delegate.cc(678)] Could not load cef.pak
[1103/220214.865127:ERROR:main_delegate.cc(695)] Could not load cef_100_percent.pak
[1103/220214.865263:ERROR:main_delegate.cc(704)] Could not load cef_200_percent.pak
[1103/220214.865379:ERROR:main_delegate.cc(713)] Could not load cef_extensions.pak
------mono runtime mode--------------
OS is: Linux
Sources: 1 Auto-dependencies: True

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'ChromiumWebBrowser, Version=3.3163.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies
File name: 'ChromiumWebBrowser, Version=3.3163.0.0, Culture=neutral, PublicKeyToken=null'
  at System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, System.Boolean refonly) [0x0003d] in <8f2c484307284b51944a1a13a14c0266>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (string,System.Security.Policy.Evidence,bool)
  at System.Reflection.Assembly.ReflectionOnlyLoad (System.String assemblyString) [0x00005] in <8f2c484307284b51944a1a13a14c0266>:0 
  at IKVM.Reflection.Universe.DefaultResolver (System.String refname, System.Boolean throwOnError) [0x00016] in <86ac282ee1f54d969d7192bd3b270156>:0 
  at IKVM.Reflection.Universe.Load (System.String refname, IKVM.Reflection.Module requestingModule, System.Boolean throwOnError) [0x00020] in <86ac282ee1f54d969d7192bd3b270156>:0 
  at IKVM.Reflection.Universe.Load (System.String refname) [0x00000] in <86ac282ee1f54d969d7192bd3b270156>:0 
  at MakeBundle.QueueAssembly (System.Collections.Generic.List`1[T] files, System.String codebase) [0x00095] in <86ac282ee1f54d969d7192bd3b270156>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'ChromiumWebBrowser, Version=3.3163.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies
File name: 'ChromiumWebBrowser, Version=3.3163.0.0, Culture=neutral, PublicKeyToken=null'
  at System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, System.Boolean refonly) [0x0003d] in <8f2c484307284b51944a1a13a14c0266>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (string,System.Security.Policy.Evidence,bool)
  at System.Reflection.Assembly.ReflectionOnlyLoad (System.String assemblyString) [0x00005] in <8f2c484307284b51944a1a13a14c0266>:0 
  at IKVM.Reflection.Universe.DefaultResolver (System.String refname, System.Boolean throwOnError) [0x00016] in <86ac282ee1f54d969d7192bd3b270156>:0 
  at IKVM.Reflection.Universe.Load (System.String refname, IKVM.Reflection.Module requestingModule, System.Boolean throwOnError) [0x00020] in <86ac282ee1f54d969d7192bd3b270156>:0 
  at IKVM.Reflection.Universe.Load (System.String refname) [0x00000] in <86ac282ee1f54d969d7192bd3b270156>:0 
  at MakeBundle.QueueAssembly (System.Collections.Generic.List`1[T] files, System.String codebase) [0x00095] in <86ac282ee1f54d969d7192bd3b270156>:0 
child cmdline:/home/lantn/testcef/testcef/testcef/bin/Debug/testcef.exe_helper --type=zygote --no-sandbox --lang=en-US --log-file=/usr/bin/debug.log
program: /home/lantn/testcef/testcef/testcef/bin/Debug/testcef.exe_helper
LaunchProcess: failed to execvp:
/home/lantn/testcef/testcef/testcef/bin/Debug/testcef.exe_helper
[1103/220216.653944:ERROR:content_client.cc(268)] No data resource available for id 20418
Segmentation fault (core dumped)

**Comment by lantianning** [comment]
一大堆文件无法找到，我已经非常迷茫了，特别是以下这一句，不知是不是关键？System.IO.FileNotFoundException: Could not load file or assembly 'ChromiumWebBrowser, Version=3.3163.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies
File name: 'ChromiumWebBrowser, Version=3.3163.0.0, Culture=neutral, PublicKeyToken=null'
另外，我查了一下论坛，将几个bin文件放去/usr/bin下了。请教大神的建议。
